language: node_js

sudo: false

node_js:
  - "5.11"

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: git.coding.net

script:
  - gulp downloadtheme
  - gulp changeavatar
  - gulp beforedeploy

branches:
  only:
    - master

deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master