language: node_js

sudo: false

node_js:
  - "5.11"

cache:
  apt: true
  directories:
    - node_modules

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master